FROM pypy:3.10-slim

# Installing dependencies for running a python application
RUN apt-get update && apt-get install -y libpq-dev postgresql-common

# Setting the working directory
WORKDIR /app

# Install pipenv dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# Copying our application into the container
COPY app /app

# Running our application
CMD ["flask", "--app", "wsgi:app", "run", "--debug", "--host", "0.0.0.0", "--port", "8080"]