services: 

  database:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: ride
    volumes: 
      - ./data/db:/var/lib/postgresql/data

  api: 
    build: .
    container_name: ridingshare
    restart: always 
    environment:
      CELERY_BROKER_URL: redis://redis:6379 
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg://administrator:verySecretPassword@database:5432/ride
    ports:
      - "8080:8080"
    depends_on:
      - database 
    command: ["flask", "--app", "wsgi:app", "run", "--debug", "--host", "0.0.0.0", "--port", "8080"]

  matching_worker:
    build: .
    restart: always
    environment:
      CELERY_BROKER_URL: redis://redis:6379 
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg://administrator:verySecretPassword@database:5432/ride
    command: celery --app tasks.celery_app worker --loglevel=info -Q matching.fifo --uid=nobody --gid=nogroup
    depends_on:
      - redis
      - database

  redis: 
    image: redis:latest 
    restart: always 
    ports: 
    - "6379:6379"