@baseUrl = http://localhost:8080

### Create a driver
POST {{baseUrl}}/driver/create
Content-Type: application/json

{
  "username": "jDoe11",
  "password": "53%32",
  "name": "John Doe",
  "phone_number": "1234567890",
  "email": "john.doe1@example.com",
  "max_available_seats": 3,
  "licence_plate": "319IRG"
}

### Create a passenger
POST {{baseUrl}}/passenger/create
Content-Type: application/json

{
  "username": "jDoe13",
  "password": "53%32",
  "name": "John Doe",
  "phone_number": "1234567890",
  "email": "john.doe1@example.com"
}

### Get a user by username
POST {{baseUrl}}/profile
Content-Type: application/json

{
  "username": "jDoe12",
  "password": "53%32",
  "user_type": "passenger"
}

### Add Trip
POST {{baseUrl}}/trip/create
Content-Type: application/json

{
  "username": "jDoe12",
  "start_time": "2024-05-10T10:00:00Z",
  "end_time": "2024-05-10T10:00:00Z",
  "start_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "123 street road, brisbane, qld"},
  "end_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "125 street road, brisbane, qld"},
  "seats_remaining": 3,
  "distance_addition": 200
}

### Add Trip
POST {{baseUrl}}/trip/create
Content-Type: application/json

{
  "username": "jDoe12",
  "start_time": "2024-05-10T11:00:00Z",
  "end_time": "2024-05-10T12:00:00Z",
  "start_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "123 street road, brisbane, qld"},
  "end_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "125 street road, brisbane, qld"},
  "seats_remaining": 3,
  "distance_addition": 100
}

### Get all trips for a user
POST {{baseUrl}}/trips/get/all
Content-Type: application/json

{
  "username": "jDoe11"
}

### Get all PENDING trips for a user
POST {{baseUrl}}/trips/get/pending
Content-Type: application/json

{
  "username": "jDoe12"
}

### Add trip request
POST {{baseUrl}}/trip_request/create
Content-Type: application/json

{
    "username": "jDoe13",
    "requested_time": "2024-05-10T11:00:00Z",
    "pickup_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "123 street road, brisbane, qld"},
    "dropoff_location": {"latitude": 37.7749, "longitude": -122.4194, "address": "125 street road, brisbane, qld"},
    "pickup_window_start": "2024-05-10T07:30:00",
    "pickup_window_end": "2024-05-10T12:00:00Z"
}

### Add trip request
POST {{baseUrl}}/trip_request/create
Content-Type: application/json

{
    "username": "jDoe12",
    "requested_time": "2024-05-10T08:00:00",
    "pickup_location": {"latitude": 37.7749, "longitude": -123.4194, "address": "123 street road, brisbane, qld"},
    "dropoff_location": {"latitude": 37.7749, "longitude": -123.4194, "address": "125 street road, brisbane, qld"},
    "pickup_window_start": "2024-05-10T07:30:00",
    "pickup_window_end": "2024-05-10T08:00:00"
}

### Get all trip requests for a user
POST {{baseUrl}}/trip_requests/get/all
Content-Type: application/json

{
  "username": "jDoe12"
}

### Get a trip requests by its id
POST {{baseUrl}}/trip_requests/get
Content-Type: application/json

{
  "trip_request_id": "735eb991-1c24-4108-896d-0f08c32eb226"
}

### Get all PENDING trip requests for a user
POST {{baseUrl}}/trip_requests/get/pending
Content-Type: application/json

{
  "username": "jDoe12",
  "trip_id": "1e866c7c-39a1-4b2e-a810-8b2b5edb1d90"
}

### Get all Nearby Trip Requests for a Driver
POST {{baseUrl}}/trip/get/pending_nearby
Content-Type: application/json

{
  "trip_id": "d0c0db22-b4ce-4578-8be5-14f5cc2b30fb",
  "username": "jDoe11"
}

### Get all Approved trip requests for a drivers trip based off time and location (could also be just time)
POST {{baseUrl}}/trip/get/approved
Content-Type: application/json

{
  "trip_id": "d0c0db22-b4ce-4578-8be5-14f5cc2b30fb",
  "username": "jDoe11"
}

### POST a Approved trip requests for a drivers trip based off time and location (could also be just time)
POST {{baseUrl}}/trip/post/approved
Content-Type: application/json

{
  "username": "jDoe11",
  "trip_request_id": "3a30e362-12a6-47bc-be26-2048494650c4",
  "trip_id": "d0c0db22-b4ce-4578-8be5-14f5cc2b30fb"
}

### GET THE TEST
GET {{baseUrl}}/test