@baseUrl = http://localhost:8080


### Create a driver
POST {{baseUrl}}/driver/create
Content-Type: application/json

{
  "username": "jDoe12",
  "name": "John Doe",
  "phone_number": "1234567890",
  "email": "john.doe1@example.com",
  "max_available_seats": 3,
  "licence_plate": "319IRG"
}

### Create a passenger
POST {{baseUrl}}/passenger/create
Content-Type: application/json

{
  "username": "jDoe12",
  "name": "John Doe",
  "phone_number": "1234567890",
  "email": "john.doe1@example.com"
}

### Get a user by username
GET {{baseUrl}}/profile
Content-Type: application/json

{
  "username": "jDoe12"
}

