name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgis/postgis
        env:
          POSTGRES_DB: ride
          POSTGRES_USER: administrator
          POSTGRES_PASSWORD: verySecretPassword
        ports:
          - 5432:5432
        # Options to keep the container running until the end of the job
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r application/requirements.txt
    
    - name: Run tests
      run: |
        export SQLALCHEMY_DATABASE_URI=postgresql+psycopg://administrator:verySecretPassword@localhost:5432/ride
        cd application/app/tests
        python -m unittest discover


